function Add () {
	var Do = document.createElement('div');
	Do.className = 'Do';
	var Title = document.createElement('input');
	Title.className = 'Title';
	Do.appendChild(Title);
	Title.setAttribute('placeholder', 'Type Title here...');
	var del = document.createElement('img');
	del.src = "Delete.png";
	Do.appendChild(del);
	del.addEventListener('click', function (e) { this.parentNode.parentNode.removeChild(this.parentNode); });
	var Description = document.createElement('textarea');
	Do.appendChild(Description);
	Description.className = 'Description';
	Description.setAttribute('placeholder', 'Type description here...');
	var date = document.createElement('div');
	date.className = 'date';
	Do.appendChild(date);
	var datetext = document.createElement('input');
	datetext.type = 'text';
	datetext.className = 'datetext';
	datetext.setAttribute('placeholder', 'when?');
	date.appendChild(datetext);
	var picker = document.createElement('input');
	picker.type = 'button';
	picker.className = 'callpicker';
	date.appendChild(picker);
	picker.addEventListener('click', function (e) { Datepicker(e); });
	this.parentNode.appendChild(Do);
};
